### ISSUE TITLE
Nav Bar Text

### ISSUE THREAD

**Issue by Taceor** [Taceor/EggZlist#13]
Looks a little cramped next to icon, and the text looks a little small on my laptop. Maybe bold or increase the size?

**Comment by rjanke** [comment]
Yeah the new header hasn't gone through the ringer yet. I need to do the icon spacing and need to make it mobile responsive. It got redone from scratch to accommodate the drop down.

**Comment by Taceor** [comment]
New header looks amazing. Closing this issue.
